version: "3"

services:
  jekyll:
    image: amirpourmand/al-folio
    command: bundler exec jekyll serve --watch --port=8080 --host=0.0.0.0 --verbose
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
